# Generated by Django 3.1 on 2020-08-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_tasks_managers', '0004_auto_20200817_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='state',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
